language: node_js
node_js:
  - "0.10"

sudo: false  # Use container-based architecture
script: >
    npm run build &&
    npm run build-tests &&
    npm run test &&
    curl -O https://raw.githubusercontent.com/danvk/travis-weigh-in/master/weigh_in.py &&
    python weigh_in.py dist/dygraph-combined.js
